### ISSUE TITLE
Add page so that a user can create a Change request

### ISSUE THREAD

**Issue by IanWorley** [X-Men-SE-CB-Fall-2023/CB-Project#26]
## In the front end build another page so that users can create a change request

- [x] Create new TSX component file
- [x] Link that component from dashboard using react router

**Comment by IanWorley** [comment]
@KyleFaris this issue can be little complicated but make sure to get the Principal as an argument makes sure the endpoint url is /api/v1/user/me

**Comment by vezr96** [comment]
React JS complement.

**Comment by IanWorley** [comment]
To make those changes public first make sure to commit the code and then please do a  ```sh git push````

**Comment by IanWorley** [comment]
@vezr96

**Comment by vezr96** [comment]
00ea3c563784bf951abe36a67901a43b69c5e57c
for later
