### ISSUE TITLE
Codebase setup not working

### ISSUE THREAD

**Issue by cbhat5** [X-Men-SE-CB-Fall-2023/CB-Project#35]
Getting ```The type org.springframework.context.ConfigurableApplicationContext cannot be resolved. It is indirectly referenced from required type org.springframework.boot.SpringApplication```

Can you please help with this or add a readme for setting up

**Comment by cbhat5** [comment]
![image](https://github.com/X-Men-SE-CB-Fall-2023/CB-Project/assets/47479435/cc1cf6e8-57f8-4273-8e91-82efd9fe6b51)

**Comment by IanWorley** [comment]
Dear @cbhat5,

Greetings! We appreciate your keen interest in our school project and your willingness to contribute. However, it's important to note that our project is not currently open source, and as such, we regret to inform you that we cannot accept your pull request or contributions at this time.

We genuinely value your enthusiasm for our project, but we must also ensure that we adhere to our institution's academic honesty policy, which you can find more information about [here](https://www.ucmo.edu/offices/general-counsel/university-policy-library/academic-policies/academic-honesty-policy/index.php). We hope you understand our commitment to maintaining the integrity of our work.

**Comment by cbhat5** [comment]
Oh. You have tagged the issues as good-first-issue, and help-wanted which leads to indexing by open-source projects sites. You can remove these or make your repo access protected/limited.

Thanks.
